[FIX] Add user and host info in bash prompt

diff --git a/shell/bash_prompt b/shell/bash_prompt
--- a/shell/bash_prompt
+++ b/shell/bash_prompt
@@ -1,141 +1,90 @@
 #!/bin/bash
 
-# bash_prompt
+## Uncomment to disable git info
+#POWERLINE_GIT=0
 
-# Example:
-# nicolas@host: ~/.dotfiles on master [+!?$]
-# $
+__powerline() {
+    # Colors
+    COLOR_RESET='\[\033[m\]'
+    COLOR_CWD=${COLOR_CWD:-'\[\033[0;34m\]'} # blue
+    COLOR_GIT=${COLOR_GIT:-'\[\033[0;36m\]'} # cyan
+    COLOR_SUCCESS=${COLOR_SUCCESS:-'\[\033[0;32m\]'} # green
+    COLOR_FAILURE=${COLOR_FAILURE:-'\[\033[0;31m\]'} # red
 
-# Screenshot: http://i.imgur.com/DSJ1G.png
-# iTerm2 prefs: import Solarized theme (disable bright colors for bold text)
-# Color ref: http://vim.wikia.com/wiki/Xterm256_color_names_for_console_Vim
-# More tips: http://www.cyberciti.biz/tips/howto-linux-unix-bash-shell-setup-prompt.html
+    # Symbols
+    SYMBOL_GIT_BRANCH=${SYMBOL_GIT_BRANCH:-⑂}
+    SYMBOL_GIT_MODIFIED=${SYMBOL_GIT_MODIFIED:-*}
+    SYMBOL_GIT_PUSH=${SYMBOL_GIT_PUSH:-↑}
+    SYMBOL_GIT_PULL=${SYMBOL_GIT_PULL:-↓}
 
-prompt_git() {
-    local s=""
-    local branchName=""
+    PS_SYMBOL='$'
 
-    # check if the current directory is in a git repository
-    if [ $(git rev-parse --is-inside-work-tree &>/dev/null; printf "%s" $?) == 0 ]; then
+    __git_info() {
+        [[ $POWERLINE_GIT = 0 ]] && return # disabled
+        hash git 2>/dev/null || return # git not found
+        local git_eng="env LANG=C git"   # force git output in English to make our work easier
 
-        # check if the current directory is in .git before running git checks
-        if [ "$(git rev-parse --is-inside-git-dir 2> /dev/null)" == "false" ]; then
+        # get current branch name
+        local ref=$($git_eng symbolic-ref --short HEAD 2>/dev/null)
 
-            # ensure index is up to date
-            git update-index --really-refresh  -q &>/dev/null
-
-            # check for uncommitted changes in the index
-            if ! $(git diff --quiet --ignore-submodules --cached); then
-                s="$s+";
-            fi
-
-            # check for unstaged changes
-            if ! $(git diff-files --quiet --ignore-submodules --); then
-                s="$s!";
-            fi
-
-            # check for untracked files
-            if [ -n "$(git ls-files --others --exclude-standard)" ]; then
-                s="$s?";
-            fi
-
-            # check for stashed files
-            if $(git rev-parse --verify refs/stash &>/dev/null); then
-                s="$s$";
-            fi
-
+        if [[ -n "$ref" ]]; then
+            # prepend branch symbol
+            ref=$SYMBOL_GIT_BRANCH$ref
+        else
+            # get tag name or short unique hash
+            ref=$($git_eng describe --tags --always 2>/dev/null)
         fi
 
-        # get the short symbolic ref
-        # if HEAD isn't a symbolic ref, get the short SHA
-        # otherwise, just give up
-        branchName="$(git symbolic-ref --quiet --short HEAD 2> /dev/null || \
-                      git rev-parse --short HEAD 2> /dev/null || \
-                      printf "(unknown)")"
+        [[ -n "$ref" ]] || return  # not a git repo
 
-        [ -n "$s" ] && s=" [$s]"
+        local marks
 
-        printf "%s" "$1$branchName$s"
-    else
-        return
-    fi
+        # scan first two lines of output from `git status`
+        while IFS= read -r line; do
+            if [[ $line =~ ^## ]]; then # header line
+                [[ $line =~ ahead\ ([0-9]+) ]] && marks+=" $SYMBOL_GIT_PUSH${BASH_REMATCH[1]}"
+                [[ $line =~ behind\ ([0-9]+) ]] && marks+=" $SYMBOL_GIT_PULL${BASH_REMATCH[1]}"
+            else # branch is modified if output contains more lines after the header line
+                marks="$SYMBOL_GIT_MODIFIED$marks"
+                break
+            fi
+        done < <($git_eng status --porcelain --branch 2>/dev/null)  # note the space between the two <
+
+        # print the git branch segment without a trailing newline
+        printf " $ref$marks"
+    }
+
+    ps1() {
+        # Check the exit code of the previous command and display different
+        # colors in the prompt accordingly.
+        if [ $? -eq 0 ]; then
+            local symbol="$COLOR_SUCCESS $PS_SYMBOL $COLOR_RESET"
+        else
+            local symbol="$COLOR_FAILURE $PS_SYMBOL $COLOR_RESET"
+        fi
+
+        local uhost="$COLOR_SUCCESS\u@\h$COLOR_RESET:"
+        local cwd="$COLOR_CWD\w$COLOR_RESET"
+        # Bash by default expands the content of PS1 unless promptvars is disabled.
+        # We must use another layer of reference to prevent expanding any user
+        # provided strings, which would cause security issues.
+        # POC: https://github.com/njhartwell/pw3nage
+        # Related fix in git-bash: https://github.com/git/git/blob/9d77b0405ce6b471cb5ce3a904368fc25e55643d/contrib/completion/git-prompt.sh#L324
+        if shopt -q promptvars; then
+            __powerline_git_info="$(__git_info)"
+            local git="$COLOR_GIT\${__powerline_git_info}$COLOR_RESET"
+        else
+            # promptvars is disabled. Avoid creating unnecessary env var.
+            local git="$COLOR_GIT$(__git_info)$COLOR_RESET"
+        fi
+
+        PS1="$uhost$cwd$git$symbol"
+
+        export PS1
+    }
+
+    PROMPT_COMMAND="ps1${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
 }
 
-set_prompts() {
-    local black=""
-    local blue=""
-    local bold=""
-    local cyan=""
-    local green=""
-    local orange=""
-    local purple=""
-    local red=""
-    local reset=""
-    local white=""
-    local yellow=""
-
-    local hostStyle=""
-    local userStyle=""
-
-    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
-        tput sgr0 # reset colors
-
-        bold=$(tput bold)
-        reset=$(tput sgr0)
-
-        # Solarized colors
-        # (https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized#the-values)
-        black=$(tput setaf 0)
-        blue=$(tput setaf 33)
-        cyan=$(tput setaf 37)
-        green=$(tput setaf 64)
-        orange=$(tput setaf 166)
-        purple=$(tput setaf 125)
-        red=$(tput setaf 124)
-        white=$(tput setaf 15)
-        yellow=$(tput setaf 136)
-    else
-        bold=""
-        reset="\e[0m"
-
-        black="\e[1;30m"
-        blue="\e[1;34m"
-        cyan="\e[1;36m"
-        green="\e[1;32m"
-        orange="\e[1;33m"
-        purple="\e[1;35m"
-        red="\e[1;31m"
-        white="\e[1;37m"
-        yellow="\e[1;33m"
-    fi
-
-    # build the prompt
-
-    # logged in as root
-    if [[ "$USER" == "root" ]]; then
-        userStyle="\[$bold$red\]"
-    else
-        userStyle="\[$orange\]"
-    fi
-
-    # connected via ssh
-    if [[ "$SSH_TTY" ]]; then
-        hostStyle="\[$bold$red\]"
-    else
-        hostStyle="\[$yellow\]"
-    fi
-
-    # set the terminal title to the current working directory
-    PS1="\[\033]0;\w\007\]"
-
-    PS1+="\n" # newline
-    PS1+="\[$green\]\w" # working directory
-    PS1+="\$(prompt_git \"$reset on $white\")" # git repository details
-    PS1+="\n"
-    PS1+="\[$reset$white\]\$ \[$reset\]" # $ (and reset color)
-
-    export PS1
-}
-
-set_prompts
-unset set_prompts
+__powerline
+unset __powerline
